# Generated by Django 4.0.4 on 2022-07-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeur', models.CharField(max_length=250)),
                ('destinataire', models.CharField(max_length=250)),
                ('notifier', models.CharField(max_length=250)),
                ('police_de_cargaison', models.CharField(max_length=250)),
                ('date_depart', models.DateField()),
                ('date_arrivee', models.DateField()),
                ('transporteur', models.CharField(max_length=250)),
                ('transitaire', models.CharField(max_length=250)),
                ('operation', models.CharField(max_length=10)),
                ('tarif', models.CharField(max_length=10)),
                ('navire_et_numeroVoyage', models.CharField(max_length=250)),
                ('port_Chargement', models.CharField(max_length=250)),
                ('port_Dechargement', models.CharField(max_length=250)),
                ('eestination_finale', models.CharField(max_length=250)),
                ('monaie', models.CharField(max_length=10)),
                ('cout_des_articles', models.FloatField()),
                ('emmision_du_besc', models.FloatField()),
                ('cout_toal', models.FloatField()),
                ('valeur_marchandise', models.FloatField()),
                ('cout_assurance', models.FloatField()),
                ('valeur_Fob', models.FloatField()),
                ('autre_valeur', models.CharField(max_length=30)),
            ],
        ),
    ]
