# Generated by Django 4.0.4 on 2022-07-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_courrier_date_arrivee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courrier',
            name='date_arrivee',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='date_depart',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
